DROP DATABASE IF EXISTS "WSO2IS_ANALYTICS_DB";
DROP DATABASE IF EXISTS "WSO2IS_ANALYTICS_CLUSTER_DB";
DROP DATABASE IF EXISTS "WSO2IS_ANALYTICS_PERSISTENCE_DB";

CREATE DATABASE "WSO2IS_ANALYTICS_DB";
CREATE DATABASE "WSO2IS_ANALYTICS_CLUSTER_DB";
CREATE DATABASE "WSO2IS_ANALYTICS_PERSISTENCE_DB";
